#!/usr/bin/env node
/**
 * Speak a film's script and report what it actually takes to say.
 *
 * This runs BEFORE the picture, on purpose. Both films lay their beats out from
 * the measured length of each synthesised line, so the timeline is a
 * consequence of the words rather than a guess at them. Rewrite a line and the
 * film retimes itself; the alternative -- writing frame counts by hand next to
 * a script -- is how narration and picture drift apart, and it is what the old
 * pipeline did.
 *
 *   node marketing/films/build-voice.mjs launch
 *   node marketing/films/build-voice.mjs walkthrough
 *
 * Writes marketing/films/out/<id>/ : one mastered WAV per beat, manifest.json
 * with the measured seconds, and a plain-text script for anyone who wants to
 * re-record it with a human voice. Every beat's audio is a separate file for
 * exactly that reason -- swapping one line does not mean re-rendering a film.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { masterLines } from "../voice/master.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "../..");
const MODEL = join(ROOT, "marketing/voice/model/kokoro.onnx");

const SCRIPTS = {
  launch: "./launch.script.mjs",
  walkthrough: "./walkthrough.script.mjs",
};

export async function buildVoice(id) {
  if (!SCRIPTS[id]) throw new Error(`unknown film ${id}; have ${Object.keys(SCRIPTS).join(", ")}`);
  if (!existsSync(MODEL)) {
    throw new Error(
      `voice model missing: ${MODEL}\nrun: bash marketing/voice/fetch-voice.sh`,
    );
  }
  const mod = await import(SCRIPTS[id]);
  const film = mod.default ?? Object.values(mod)[0];

  const outDir = join(HERE, "out", id);
  const rawDir = join(outDir, "raw");
  mkdirSync(rawDir, { recursive: true });

  const spec = {
    outDir: rawDir,
    // Kokoro's `speed` is the inverse of Piper's old `length_scale`: 1.0 is its
    // natural pace and it genuinely is natural, so the films no longer stretch
    // it. The scripts kept a `length` of 1.04 and 1.07 to slow Piper down,
    // which was compensating for a voice that read like a form.
    ...(film.voice ? { voice: film.voice } : {}),
    ...(film.speed ? { speed: film.speed } : {}),
    lines: film.beats.map((b) => ({
      id: b.id,
      text: b.vo,
      ...(b.speed ? { speed: b.speed } : {}),
    })),
  };

  console.error(`\n${id}: speaking ${spec.lines.length} lines`);
  const rawManifest = join(rawDir, "manifest.json");
  const stdout = execFileSync("python3", [join(ROOT, "marketing/voice/synth.py")], {
    input: JSON.stringify(spec),
    encoding: "utf8",
    stdio: ["pipe", "pipe", "inherit"],
    cwd: ROOT,
  });
  writeFileSync(rawManifest, stdout);

  console.error(`${id}: mastering`);
  const mastered = masterLines(rawManifest, outDir);

  // Fold the script's holds back in, so the manifest describes BEATS rather
  // than bare audio -- everything downstream wants beat lengths.
  const byId = new Map(film.beats.map((b) => [b.id, b]));
  let at = 0;
  const beats = mastered.lines.map((line) => {
    const beat = byId.get(line.id);
    const hold = beat?.hold ?? 0;
    const row = {
      ...line,
      hold,
      /** When the line starts, and how long the whole beat runs. */
      startsAt: Number(at.toFixed(3)),
      beatSeconds: Number((line.seconds + hold).toFixed(3)),
      ...(beat?.shot ? { shot: beat.shot } : {}),
      ...(beat?.nav !== undefined ? { nav: beat.nav } : {}),
      ...(beat?.scroll ? { scroll: beat.scroll } : {}),
      ...(beat?.cutTo ? { cutTo: beat.cutTo } : {}),
    };
    at += row.beatSeconds;
    return row;
  });

  const manifest = {
    id,
    voice: "en_US-joe-medium (Piper, CC0), synthesised locally",
    seconds: Number(at.toFixed(3)),
    beats,
  };
  writeFileSync(join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2));

  // A plain script, timestamped, for re-recording with a human voice later.
  const stamp = (s) =>
    `${String(Math.floor(s / 60)).padStart(2, "0")}:${(s % 60).toFixed(1).padStart(4, "0")}`;
  writeFileSync(
    join(outDir, "script.txt"),
    [
      `${id} — voiceover script`,
      `total ${manifest.seconds.toFixed(1)}s across ${beats.length} beats`,
      "",
      ...beats.map((b) => `[${stamp(b.startsAt)}]  ${b.id}\n  ${b.text}\n`),
    ].join("\n"),
  );

  // Hand the timing to Remotion as a module it can import directly. A JSON
  // fetch at render time would be one more thing to fail inside a headless
  // browser; a generated .ts is checked by the same compiler as the film.
  const timingDir = join(ROOT, "marketing/remotion/src/generated");
  mkdirSync(timingDir, { recursive: true });
  writeFileSync(
    join(timingDir, `${id}Timing.ts`),
    [
      "// GENERATED by marketing/films/build-voice.mjs -- do not edit.",
      "//",
      "// The measured length of every spoken line, so the picture is cut to the",
      "// narration rather than the other way round. Re-run build-voice after any",
      "// script change and the film retimes itself.",
      `// voice: ${manifest.voice}`,
      "",
      "export interface Beat {",
      "  id: string;",
      "  shot?: string;",
      "  /** Seconds of speech. */",
      "  seconds: number;",
      "  /** Dead air after the line, in seconds. */",
      "  hold: number;",
      "  /** Seconds from the start of the film. */",
      "  startsAt: number;",
      "  /** seconds + hold. */",
      "  beatSeconds: number;",
      "  text: string;",
      "}",
      "",
      `export const TOTAL_SECONDS = ${manifest.seconds};`,
      "",
      "export const BEATS: Beat[] = [",
      ...beats.map(
        (b) =>
          "  " +
          JSON.stringify({
            id: b.id,
            ...(b.shot ? { shot: b.shot } : {}),
            seconds: b.seconds,
            hold: b.hold,
            startsAt: b.startsAt,
            beatSeconds: b.beatSeconds,
            text: b.text,
          }) +
          ",",
      ),
      "];",
      "",
      "/** Beat lookup by id, for a composition that names its shots. */",
      "export const beat = (id: string): Beat => {",
      "  const found = BEATS.find((b) => b.id === id);",
      "  if (!found) throw new Error(`no beat ${id}; regenerate with build-voice.mjs`);",
      "  return found;",
      "};",
      "",
    ].join("\n"),
  );

  console.error(`${id}: ${manifest.seconds.toFixed(1)}s total -> ${outDir}`);
  return manifest;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2];
  if (!id) {
    console.error(`usage: build-voice.mjs <${Object.keys(SCRIPTS).join("|")}>`);
    process.exit(1);
  }
  await buildVoice(id);
}
